
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIONS ASSIGNMENT BOOL CBLOCK CLIB COLON DESCRIPTION EOL EXPRESSION FALSE INOUT INT INTOUT LINE LPARENT NAME NUMBER RPAREN SHELFS SKEWERS SPACE TITLE TRUE TYPE VARIABLESdesc : TITLE COLON SPACE LINE EOLclib : CLIB COLON SPACE LINE EOLprogram : desc clib'
    
_lr_action_items = {'COLON':([2,],[3,]),'$end':([1,6,],[0,-1,]),'EOL':([5,],[6,]),'LINE':([4,],[5,]),'TITLE':([0,],[2,]),'SPACE':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'desc':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> desc","S'",1,None,None,None),
  ('desc -> TITLE COLON SPACE LINE EOL','desc',5,'p_desc','parser.py',7),
  ('clib -> CLIB COLON SPACE LINE EOL','clib',5,'p_clib','parser.py',10),
  ('program -> desc clib','program',2,'p_program','parser.py',13),
]
