
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIONS ASSIGNMENT BOOL CBLOCK COLON DESCRIPTION END EOL EXPRESSION ID IN INT INTOUT ITEMS NATIVE_LIBRARY NUMBER OUT SHELFS SKEWERS SPACE START_SKEWER SVG TITLE TYPE VARIABLES WORDprogram : title EOL native_library EOL variables EOL actions shelfs end EOL skewersdescription : DESCRIPTION COLON SPACE string EOLskewers : SKEWERS COLON EOL skwrsskwrs : skewer EOL svg\n             | skewer EOL svg skwrssvg : SPACE SVG COLON EOL svgdef EOLsvgdef : SPACE string EOL\n              | SPACE string EOL svgdefskewer : SPACE WORD COLON EOL SPACE ITEMS COLON SPACE string\n              | SPACE WORD COLON EOL SPACE ITEMS COLON SPACE string SPACE ENDactions : ACTIONS COLON EOL EOL\n               | ACTIONS COLON EOL actsshelfs : SHELFS COLON EOL\n              | SHELFS COLON EOL shlfsshlfs : shelf EOL\n             | shelf EOL shlfsacts : action EOL\n            | action EOL actsshelf : SPACE WORD COLON EOL SPACE DESCRIPTION COLON SPACE string SPACE ASSIGNMENT                SPACE string EOL SPACE EXPRESSION COLON SPACE WORD SPACE ASSIGNMENT SPACE string EOL svgaction : SPACE WORD COLON EOL SPACE description SPACE cblock EOL svgcblock : CBLOCK COLON SPACE methods EOLmethods : methoddef\n               | methods EOL SPACE methoddefmethoddef : stringvariables : VARIABLES COLON vars EOLvars :\n            | var\n            | vars EOL varinout : IN\n             | OUTvtype : INT\n             | BOOL var : SPACE inout SPACE WORD SPACE vtype SPACE stringtitle : TITLE COLON EOL SPACE description SPACE START_SKEWER COLON SPACE WORD EOL svgnative_library : NATIVE_LIBRARY COLON SPACE WORD EOLstring : WORDstring : string SPACE WORDend : END COLON EOL svg'
    
_lr_action_items = {'EXPRESSION':([137,],[138,]),'ASSIGNMENT':([122,142,],[127,143,]),'COLON':([3,6,14,15,24,29,31,41,60,66,73,81,93,102,110,116,138,],[5,9,19,20,32,39,42,50,69,75,83,89,98,108,115,121,139,]),'NATIVE_LIBRARY':([4,],[6,]),'CBLOCK':([103,],[110,]),'INT':([67,],[78,]),'DESCRIPTION':([11,91,96,],[15,15,102,]),'ACTIONS':([18,],[24,]),'VARIABLES':([10,],[14,]),'START_SKEWER':([21,],[29,]),'SKEWERS':([49,],[60,]),'SVG':([71,],[81,]),'BOOL':([67,],[77,]),'SPACE':([8,9,16,19,20,33,34,35,36,37,38,39,43,46,51,56,57,61,65,68,72,76,77,78,80,84,90,92,94,95,97,99,104,106,107,108,112,114,115,118,121,123,127,128,129,133,136,139,141,143,145,146,],[11,12,21,27,28,27,45,-30,-29,47,-36,48,55,-2,64,67,-37,71,55,71,64,85,-32,-31,87,91,96,47,71,101,103,87,111,-6,47,113,101,71,120,122,126,47,130,131,132,47,137,140,142,144,47,71,]),'END':([30,51,62,72,82,132,],[41,-13,-14,-15,-16,135,]),'SHELFS':([23,52,53,65,74,],[31,-11,-12,-17,-18,]),'IN':([27,],[36,]),'OUT':([27,],[35,]),'TITLE':([0,],[3,]),'$end':([2,59,86,99,105,106,],[0,-1,-3,-4,-5,-6,]),'ITEMS':([111,],[116,]),'WORD':([12,28,45,47,48,55,64,85,87,101,113,120,122,126,130,131,132,140,144,],[17,38,56,57,58,66,73,38,93,38,38,38,57,38,38,38,57,141,38,]),'EOL':([1,5,7,13,17,19,22,25,26,32,33,37,38,40,42,43,44,50,54,57,58,63,69,70,75,79,83,88,89,92,98,100,106,107,109,112,117,119,123,124,125,128,129,133,134,135,145,147,],[4,8,10,18,22,-26,-35,33,-27,43,-25,46,-36,49,51,52,-28,61,65,-37,68,72,80,-38,84,-34,90,94,95,-33,104,106,-6,112,114,-7,-8,-20,-24,-22,128,-21,-9,136,-23,-10,146,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'string':([28,85,101,113,120,126,130,131,144,],[37,92,107,118,123,129,133,123,145,]),'variables':([10,],[13,]),'acts':([43,65,],[53,74,]),'native_library':([4,],[7,]),'action':([43,65,],[54,54,]),'vtype':([67,],[76,]),'vars':([19,],[25,]),'actions':([18,],[23,]),'methoddef':([120,131,],[124,134,]),'shelf':([51,72,],[63,63,]),'skwrs':([80,99,],[86,105,]),'svgdef':([95,112,],[100,117,]),'var':([19,33,],[26,44,]),'title':([0,],[1,]),'end':([30,],[40,]),'methods':([120,],[125,]),'description':([11,91,],[16,97,]),'shelfs':([23,],[30,]),'skewer':([80,99,],[88,88,]),'inout':([27,],[34,]),'skewers':([49,],[59,]),'shlfs':([51,72,],[62,82,]),'program':([0,],[2,]),'cblock':([103,],[109,]),'svg':([61,68,94,114,146,],[70,79,99,119,147,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> title EOL native_library EOL variables EOL actions shelfs end EOL skewers','program',11,'p_program','program_parser.py',61),
  ('description -> DESCRIPTION COLON SPACE string EOL','description',5,'p_description','program_parser.py',65),
  ('skewers -> SKEWERS COLON EOL skwrs','skewers',4,'p_skewers','program_parser.py',70),
  ('skwrs -> skewer EOL svg','skwrs',3,'p_skwrs','program_parser.py',74),
  ('skwrs -> skewer EOL svg skwrs','skwrs',4,'p_skwrs','program_parser.py',75),
  ('svg -> SPACE SVG COLON EOL svgdef EOL','svg',6,'p_svg','program_parser.py',79),
  ('svgdef -> SPACE string EOL','svgdef',3,'p_svgdef','program_parser.py',82),
  ('svgdef -> SPACE string EOL svgdef','svgdef',4,'p_svgdef','program_parser.py',83),
  ('skewer -> SPACE WORD COLON EOL SPACE ITEMS COLON SPACE string','skewer',9,'p_skewer','program_parser.py',87),
  ('skewer -> SPACE WORD COLON EOL SPACE ITEMS COLON SPACE string SPACE END','skewer',11,'p_skewer','program_parser.py',88),
  ('actions -> ACTIONS COLON EOL EOL','actions',4,'p_actions','program_parser.py',103),
  ('actions -> ACTIONS COLON EOL acts','actions',4,'p_actions','program_parser.py',104),
  ('shelfs -> SHELFS COLON EOL','shelfs',3,'p_shelfs','program_parser.py',108),
  ('shelfs -> SHELFS COLON EOL shlfs','shelfs',4,'p_shelfs','program_parser.py',109),
  ('shlfs -> shelf EOL','shlfs',2,'p_shlfs','program_parser.py',113),
  ('shlfs -> shelf EOL shlfs','shlfs',3,'p_shlfs','program_parser.py',114),
  ('acts -> action EOL','acts',2,'p_acts','program_parser.py',118),
  ('acts -> action EOL acts','acts',3,'p_acts','program_parser.py',119),
  ('shelf -> SPACE WORD COLON EOL SPACE DESCRIPTION COLON SPACE string SPACE ASSIGNMENT SPACE string EOL SPACE EXPRESSION COLON SPACE WORD SPACE ASSIGNMENT SPACE string EOL svg','shelf',25,'p_shelf','program_parser.py',123),
  ('action -> SPACE WORD COLON EOL SPACE description SPACE cblock EOL svg','action',10,'p_action','program_parser.py',135),
  ('cblock -> CBLOCK COLON SPACE methods EOL','cblock',5,'p_cblock','program_parser.py',150),
  ('methods -> methoddef','methods',1,'p_methods','program_parser.py',154),
  ('methods -> methods EOL SPACE methoddef','methods',4,'p_methods','program_parser.py',155),
  ('methoddef -> string','methoddef',1,'p_methoddef','program_parser.py',167),
  ('variables -> VARIABLES COLON vars EOL','variables',4,'p_variables','program_parser.py',208),
  ('vars -> <empty>','vars',0,'p_vars','program_parser.py',220),
  ('vars -> var','vars',1,'p_vars','program_parser.py',221),
  ('vars -> vars EOL var','vars',3,'p_vars','program_parser.py',222),
  ('inout -> IN','inout',1,'p_inout','program_parser.py',226),
  ('inout -> OUT','inout',1,'p_inout','program_parser.py',227),
  ('vtype -> INT','vtype',1,'p_vtype','program_parser.py',235),
  ('vtype -> BOOL','vtype',1,'p_vtype','program_parser.py',236),
  ('var -> SPACE inout SPACE WORD SPACE vtype SPACE string','var',8,'p_var','program_parser.py',241),
  ('title -> TITLE COLON EOL SPACE description SPACE START_SKEWER COLON SPACE WORD EOL svg','title',12,'p_title','program_parser.py',251),
  ('native_library -> NATIVE_LIBRARY COLON SPACE WORD EOL','native_library',5,'p_native_library','program_parser.py',261),
  ('string -> WORD','string',1,'p_string_word','program_parser.py',297),
  ('string -> string SPACE WORD','string',3,'p_string_row','program_parser.py',302),
  ('end -> END COLON EOL svg','end',4,'p_end','program_parser.py',307),
]
